# Generated by AI to create a CSV of daily YouTube topic summaries, similar to GDELT institutional_news.csv layout
import pandas as pd

INPUT_CSV = "youtube_all_topics_by_timestamp.csv"
OUTPUT_CSV = "youtube_topics_daily_summary.csv"

df = pd.read_csv(INPUT_CSV)

df["published_dt"] = pd.to_datetime(df["publishedAt"], errors="coerce", utc=True)
df = df.dropna(subset=["published_dt"])

df["date"] = df["published_dt"].dt.strftime("%Y-%m-%d")
df["date_yyyymmdd"] = df["published_dt"].dt.strftime("%Y%m%d").astype(int)

for col in ["viewCount", "likeCount", "commentCount"]:
    df[col] = pd.to_numeric(df[col], errors="coerce")

agg = (
    df.groupby(["date_yyyymmdd", "date", "theme"], dropna=False)
      .agg(
          video_count=("videoId", "count"),
          viewcount_avg=("viewCount", "mean"),
          viewcount_sum=("viewCount", "sum"),
          likecount_avg=("likeCount", "mean"),
          likecount_sum=("likeCount", "sum"),
          commentcount_avg=("commentCount", "mean"),
          commentcount_sum=("commentCount", "sum"),
      )
      .reset_index()
)

agg = agg.sort_values(["date_yyyymmdd", "theme"])
for c in ["viewcount_avg", "likecount_avg", "commentcount_avg"]:
    agg[c] = agg[c].round(2)

agg.to_csv(OUTPUT_CSV, index=False)

print(f"Saved: {OUTPUT_CSV}")
print(agg.head(10))
