# Generated by AI to combine multiple YouTube topic JSON files into one CSV
import json
import pandas as pd
from pathlib import Path

FILES = {
    "election": Path("youtube_raw_election_combined.json"),
    "immigration": Path("youtube_raw_immigration_combined.json"),
    "conflict": Path("youtube_raw_conflict.json"),
}

rows = []

def to_int(x):
    try:
        return int(x)
    except:
        return None

for theme, path in FILES.items():
    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)

    for item in data.get("items", []):
        snippet = item.get("snippet", {}) or {}
        stats = item.get("statistics", {}) or {}

        published = snippet.get("publishedAt")
        published_dt = pd.to_datetime(published, errors="coerce")

        rows.append({
            "videoId": item.get("id"),
            "date": published_dt.date() if not pd.isna(published_dt) else None,
            "publishedAt": published,
            "theme": theme,
            "title": snippet.get("title"),
            "channelTitle": snippet.get("channelTitle"),
            "viewCount": to_int(stats.get("viewCount")),
            "likeCount": to_int(stats.get("likeCount")),
            "commentCount": to_int(stats.get("commentCount")),
        })

df = pd.DataFrame(rows)

df["published_dt"] = pd.to_datetime(df["publishedAt"], errors="coerce")
df = df.sort_values("published_dt").drop(columns=["published_dt"])

df = df[
    [
        "videoId",
        "date",
        "publishedAt",
        "theme",
        "title",
        "channelTitle",
        "viewCount",
        "likeCount",
        "commentCount",
    ]
]

df.to_csv("youtube_all_topics_by_timestamp.csv", index=False)

print("Saved youtube_all_topics_by_timestamp.csv")
print("Total videos:", len(df))