# Generated by AI to create a CSV of top YouTube channels
import pandas as pd

INPUT_CSV = "youtube_all_topics_by_timestamp.csv"
OUTPUT_CSV = "youtube_top_channels_by_topic.csv"

df = pd.read_csv(INPUT_CSV)

required = ["channelTitle", "theme", "videoId"]
missing = [c for c in required if c not in df.columns]
if missing:
    raise ValueError(f"Missing columns: {missing}. Found: {list(df.columns)}")

df = df.dropna(subset=["channelTitle", "theme", "videoId"])

pivot = (
    df.pivot_table(
        index="channelTitle",
        columns="theme",
        values="videoId",
        aggfunc="count",
        fill_value=0
    )
    .reset_index()
)

topic_cols = [c for c in pivot.columns if c != "channelTitle"]
pivot["total_videos"] = pivot[topic_cols].sum(axis=1)

pivot = pivot[["channelTitle", "total_videos"] + sorted(topic_cols)]

top10 = pivot.sort_values("total_videos", ascending=False).head(10)

top10.to_csv(OUTPUT_CSV, index=False)
print(f"Saved: {OUTPUT_CSV}")
print(top10)